@startuml
'usecase "Use Case"
'
'usecase UC1 as "Use Case 1"
'usecase UC2 as "Use Case 2"
'
'actor "Actor"
'
'actor A1 as "Actor 1"
'actor A2 as "Actor 2"
'
'actor A1 as "Actor 1"
'usecase UC1 as "Use Case 1"
'
'A1 --> UC1
'
'rectangle Database
'
'rectangle System {
'    usecase UC1 as "Use Case 1"
'    UC1 --> Database
'}
actor HR as "HR Advisor"

rectangle Database

rectangle "HR System" {
    usecase UC4 as "Get salaries
    by role"

    usecase UCa as "Print salaries"

    HR - UC4
    UC4 ..> UCa : include
    UC4 - Database
}
'Alice -> Bob: Authentication Request
'Bob --> Alice: Authentication Response
'
'Alice -> Bob: Another authentication Request
'Alice <-- Bob: another authentication Response
@enduml